### ISSUE TITLE
[UBUNTU] MyTonCtrl Status throwing error

### ISSUE THREAD

**Issue by kr4t0z** [igroman787/mytonctrl#35]
First of all, I'm sorry if my english is bad.

Hi everyone, i'm triyng to install myTonCtrl in my Azure VPS but after the installation process i'm getting this error when try to run the status command:

`MyTonCtrl> status`
`Error: 'NoneType' object has no attribute 'GetValidatorStatus'`

I have no idea what to do, can someone help me please?

**Comment by kesha-antonov** [comment]
Same

**Comment by igroman787** [comment]
The error itself says that the configuration file is corrupted:
~/.local/share/mytoncore/mytoncore.db
or
/usr/local/bin/mytoncore/mytoncore.db

In the near future, I plan to add a more subgeneric error message instead of this error. It will also try to recover these files by itself. But so far there is no such thing.

There may be several reasons for this error:
1. The installation went wrong - something could get up badly.
2. We installed mytonctrl as one user, and we run as another user.
3. Due to lack of space on the VPS, configuration files could be damaged (not only mytonctrl) - it will take a long time to restore these files.

As a solution, you can copy the spare configuration files (and do not forget to correct the file permissions to avoid the "access denied" error):
cp ~/.local/share/mytoncore/mytoncore.db.backup ~/.local/share/mytoncore/mytoncore.db

Also, if the configuration files of the validator were damaged, they will also have to be corrected. The validator configuration file is located here:
/var/ton-work/db/config.json

**Comment by kr4t0z** [comment]
I followed your steps and copied the spare configuration files. It worked. Thank you very much!

**Comment by ntohidi** [comment]
hi @igroman787 

I've tried the solution here, but it didn't work, and when I use `emi` command, it gives me the same error
and it says that the config file is broken. I actually couldn't find /var/ton-work/db/config.json that you mentioned here.

my system is an AWS ec2 instance, ubuntu 20.4.
![image](https://user-images.githubusercontent.com/17140097/147087799-26466588-d2d5-4689-85a3-1f9c8814e72f.png)

**Comment by ntohidi** [comment]
I found the solution! I installed mytonctrl as one user(root), and I was running it with another user. All I had to do was: 
`sudo mytonctrl`
